// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTJaZafBK7vmob1hXX9lYN_SdX59x9RZc',
    appId: '1:628856085922:web:78902a938fd24ba283e6fb',
    messagingSenderId: '628856085922',
    projectId: 'smartstock-ae7ad',
    authDomain: 'smartstock-ae7ad.firebaseapp.com',
    storageBucket: 'smartstock-ae7ad.firebasestorage.app',
    measurementId: 'G-TRRG4YRHG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGCurTrUTmnLCD7NhXLe3u072vxrab9Y',
    appId: '1:628856085922:android:a0ca8f6d7c6bb58483e6fb',
    messagingSenderId: '628856085922',
    projectId: 'smartstock-ae7ad',
    storageBucket: 'smartstock-ae7ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFtf4z-HGz8PbTHFgw3ThLhGTHGzWBx0',
    appId: '1:628856085922:ios:50d12ba0f894e02883e6fb',
    messagingSenderId: '628856085922',
    projectId: 'smartstock-ae7ad',
    storageBucket: 'smartstock-ae7ad.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJFtf4z-HGz8PbTHFgw3ThLhGTHGzWBx0',
    appId: '1:628856085922:ios:50d12ba0f894e02883e6fb',
    messagingSenderId: '628856085922',
    projectId: 'smartstock-ae7ad',
    storageBucket: 'smartstock-ae7ad.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTJaZafBK7vmob1hXX9lYN_SdX59x9RZc',
    appId: '1:628856085922:web:d4d14fd7f7ec917683e6fb',
    messagingSenderId: '628856085922',
    projectId: 'smartstock-ae7ad',
    authDomain: 'smartstock-ae7ad.firebaseapp.com',
    storageBucket: 'smartstock-ae7ad.firebasestorage.app',
    measurementId: 'G-G2Q16BCXY6',
  );
}
